# ServiceNow Developer Instance Provisioning - Job Template Configuration

# This is a reference file for setting up the AAP job template correctly.
# Note: This is not used directly by AAP, but serves as documentation.

---
job_template:
  name: "ServiceNow Developer Instance Provisioning"
  description: "Automates the provisioning of ServiceNow developer instances"
  job_type: "run"
  inventory: "localhost"
  project: "Demo AAP Post-Deploy"
  playbook: "playbooks/service_now/provision-servicenow-dev.yml"
  credential: "localhost-machine-credential"
  verbosity: 1
  ask_variables_on_launch: true
  ask_limit_on_launch: false
  ask_tags_on_launch: false
  ask_skip_tags_on_launch: false
  ask_job_type_on_launch: false
  ask_inventory_on_launch: false
  ask_credential_on_launch: false
  survey_enabled: true
  survey_spec:
    name: "ServiceNow Developer Instance Provisioning"
    description: "Gathers required information for ServiceNow developer instance provisioning"
    spec:
      - question_name: "ServiceNow Developer Portal Username"
        question_description: "Your username (email) for the ServiceNow Developer Portal"
        required: true
        type: "text"
        variable: "servicenow_dev_username"
        default: ""
        
      - question_name: "ServiceNow Developer Portal Password"
        question_description: "Your password for the ServiceNow Developer Portal"
        required: true
        type: "password"
        variable: "servicenow_dev_password"
        default: ""
        
      - question_name: "Desired Instance Name (optional)"
        question_description: "If left blank, a unique name will be auto-generated"
        required: false
        type: "text"
        variable: "instance_name"
        default: ""
        
      - question_name: "Poll Interval in seconds"
        question_description: "Time between status checks (in seconds)"
        required: false
        type: "integer"
        variable: "poll_interval"
        default: 60
        min: 10
        max: 300
        
      - question_name: "Maximum Timeout in seconds"
        question_description: "Maximum wait time before giving up (in seconds)"
        required: false
        type: "integer"
        variable: "timeout"
        default: 1800
        min: 300
        max: 3600
  extra_vars:
    poll_interval: 60
    timeout: 1800
