---
- name: Apply compliance profile
  hosts: all
  become: true
  vars:
    compliance_profile: undef
    demo_mode: false  # Add this variable

  tasks:
    - name: Check os type
      ansible.builtin.assert:
        that: "ansible_os_family == 'RedHat'"
      tags: always

    - name: Run Security Compliance Profile (Demo Mode - Simulated)
      ansible.builtin.debug:
        msg:
          - "DEMO MODE: Security compliance profile would be applied"
          - "Profile: redhatofficial.rhel{{ ansible_distribution_major_version }}_{{ compliance_profile }}"
          - "In production, this would apply {{ compliance_profile }} hardening rules"
      when: demo_mode | bool
      tags: always

    - name: Run Security Compliance Profile (Full Mode)
      ansible.builtin.include_role:
        name: "redhatofficial.rhel{{ ansible_distribution_major_version }}_{{ compliance_profile }}"
      vars:
        sudo_require_authentication: false
        sudo_remove_nopasswd: false
        reboot_required: false
        medium_severity: false
      when: not (demo_mode | bool)
      tags: always
