- name: Get Event Detail
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Debug all vars
      ansible.builtin.debug:
        var: ansible_eda

    # For Testing
    - name: Pass the event detail
      ansible.builtin.set_stats:
        data:
          tfc_workspace_id: "{{ ansible_eda.event.payload.details.workspace_id }}"
          tfc_workspace_name: "{{ ansible_eda.event.payload.details.workspace_name }}"
          tfc_assessment_result_url: "{{ ansible_eda.event.payload.details.new_assessment_result.url }}"
          var_inc_desc: "Drift Detected"
          var_inc_sn_desc: |-
            Drift Detected with the following Detail:
            {{ ansible_eda.event.payload.details }}
