---
- name: Remediate Config Drift from TFC
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    terraform_action: plan
    workspace_id: "{{ tfc_workspace_id }}"

  roles:
    - terraform_cloud

  post_tasks:
    
    - name: Update an incident in ServiceNow
      servicenow.itsm.incident:
        state: in_progress
        number: "{{ ticket_number }}"
        other:
          comments: "{{ terraformplanresult.content | from_json }}"
      delegate_to: localhost

    - name: Pass Plan Response
      ansible.builtin.set_stats:
        data:
          terraformplanresponse: "{{ terraformplanresponse }}"
  
