---
- name: Remediate Config Drift from TFC
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    terraform_action: plan

  roles:
    - terraform_cloud

  post_tasks:
    
    - name: Update an incident in ServiceNow
      servicenow.itsm.incident:
        state: in_progress
        number: "{{ ticket_number }}"
      vars:
        comment: "Terraform Plan"
      delegate_to: localhost
