---
- name: Create an incident in ServiceNow using facts from a host
  hosts: all
  gather_facts: false
  connection: local

  pre_tasks:
  - name: Set variables
    ansible.builtin.set_fact:
      servicenow_ticket: create
      incident_description: "{{ var_inc_desc | default('Provisioning has been failed') }}"
      sn_description: "{{ var_inc_sn_desc | default('Provisioning has been failed') }}"
      
    run_once: yes

  roles:
    - demo.process.snow_ticket
  run_once: yes
