---
- name: Close a change request
  hosts: all
  gather_facts: false
  connection: local

  vars:
    servicenow_cr: close
    close_code: "{{ cr_close_status |default('successful')}}"
    close_notes: "Change is closed with {{ cr_close_status |default('successful')}} provision"
    # change_request_number: "{{ request.record.number | default(omit) }}"

  roles:
    - demo.process.snow_change_request
  run_once: yes