---
- name: Send POST request using uri module to apply the plan
  ansible.builtin.uri:
    url: "https://app.terraform.io/api/v2/runs/{{ terraformplanresponse.json.data.id }}/actions/apply"
    method: POST
    headers:
      Content-Type: "application/vnd.api+json"
      Authorization: "Bearer {{ hcpterraform_api_token }}"
    body: |-
      {
        "comment": "approved using Change Request Number: {{ request.record.task_effective_number }}"
      }
    status_code: 202
    timeout: 60
  register: terraformapplyresponse

- name: Send Get request using uri module to get run status completed
  ansible.builtin.uri:
    url: "https://app.terraform.io/api/v2/runs/{{ terraformapplyresponse.json.data.id }}"
    headers:
      Content-Type: "application/vnd.api+json"
      Authorization: "Bearer {{ hcpterraform_api_token }}"
    status_code: 200
    body_format: json
    return_content: true
    timeout: 60
  register: terraformrunstatus
  retries: 50
  until: terraformrunstatus.json.data.attributes.status == "applied"
